import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Navbar from '@/components/Navbar'
import Main from '@/components/Main'
import About from '@/components/About'

export default function Home() {
  return (
  <div>
      <head>
        <title>Kelvin |Front-End Developer </title>
      <meta name="description" content='Generated by Create next App'/>
      <link rel='icon' href='favicon.ico'/>
      </head>
      <Navbar/>
      <Main/>
      <About/>
  </div>
  )
}
